name: ${project.name}
main: io.github.lambdaphoenix.advancementLib.DummyMain
version: ${project.version}
description: ${project.description}
website: ${project.url}
authors:
  - lambdaphoenix
api-version: 1.20